const cloud = { client: null, session: null, user: null, config: null, saveTimer: null, listenerBound: false, saving: false, allowLocalOnly: false, hydrated: false, google: { connected: false, calendarId: '', calendarName: '', googleEmail: '', lastError: '', lastSyncAt: '', syncing: false }, googleQueue: Promise.resolve() };

const state = {
  clients: [],
  packages: [],
  plans: [],
  lessons: [],
  selectedClientId: null,
  selectedLessonId: null,
  selectedDay: todayISO(),
  selectedPackageId: null,
  viewDate: startOfMonth(new Date()),
  calendarView: 'month',
  search: '',
  clientFilter: 'all',
  heroAlertsExpanded: false,
  calendarQuickSearch: '',
  googleBlockingBusy: [],
  googleBlockingBusyKey: '',
  pendingAdd: null,
  pendingTimeValue: '',
  reportOpenedOnce: false,
  dismissedAlerts: []
};

const derived = {
  lessonsByDate: null
};

function invalidateDerivedData() {
  derived.lessonsByDate = null;
}

const el = {
  heroSubtitle: document.getElementById('heroSubtitle'),
  heroInsights: document.getElementById('heroInsights'),
  heroStats: document.getElementById('heroStats'),
  opsBoard: document.getElementById('opsBoard'),
  selectedClientCard: document.getElementById('selectedClientCard'),
  mobileSelectedClientCard: document.getElementById('mobileSelectedClientCard'),
  alertStrip: document.getElementById('alertStrip'),
  clientCountTag: document.getElementById('clientCountTag'),
  clientSearch: document.getElementById('clientSearch'),
  clientFilterRow: document.getElementById('clientFilterRow'),
  clientList: document.getElementById('clientList'),
  monthLabel: document.getElementById('monthLabel'),
  calendarMeta: document.getElementById('calendarMeta'),
  calendarHead: document.getElementById('calendarHead'),
  calendarGrid: document.getElementById('calendarGrid'),
  agendaWrap: document.getElementById('agendaWrap'),
  calendarQuickSearch: document.getElementById('calendarQuickSearch'),
  calendarQuickSearchResults: document.getElementById('calendarQuickSearchResults'),
  calendarViewButtons: [...document.querySelectorAll('[data-calendar-view]')],
  toast: document.getElementById('toast'),

  clientModalBackdrop: document.getElementById('clientModalBackdrop'),
  clientModalTitle: document.getElementById('clientModalTitle'),
  clientForm: document.getElementById('clientForm'),
  clientId: document.getElementById('clientId'),
  clientPlanId: document.getElementById('clientPlanId'),
  clientName: document.getElementById('clientName'),
  clientSurname: document.getElementById('clientSurname'),
  clientEmail: document.getElementById('clientEmail'),
  clientSendCalendarInvite: document.getElementById('clientSendCalendarInvite'),
  clientServiceType: document.getElementById('clientServiceType'),
  clientPackage: document.getElementById('clientPackage'),
  clientPackagePrice: document.getElementById('clientPackagePrice'),
  clientStartDate: document.getElementById('clientStartDate'),
  clientFreeSessionDone: document.getElementById('clientFreeSessionDone'),
  clientPackagePurchased: document.getElementById('clientPackagePurchased'),
  clientConversionStatus: document.getElementById('clientConversionStatus'),
  clientPaymentStatus: document.getElementById('clientPaymentStatus'),
  clientPaymentMode: document.getElementById('clientPaymentMode'),
  clientInstallmentsRow: document.getElementById('clientInstallmentsRow'),
  clientInstallmentsTotal: document.getElementById('clientInstallmentsTotal'),
  clientInstallmentsPaid: document.getElementById('clientInstallmentsPaid'),
  clientHistoryWrap: document.getElementById('clientHistoryWrap'),
  clientPaymentHistory: document.getElementById('clientPaymentHistory'),
  clientRenewalHistory: document.getElementById('clientRenewalHistory'),
  clientAppointmentsWrap: document.getElementById('clientAppointmentsWrap'),
  clientAppointmentsList: document.getElementById('clientAppointmentsList'),
  copyAppointmentsBtn: document.getElementById('copyAppointmentsBtn'),
  clientFixedTime: document.getElementById('clientFixedTime'),
  clientWeekdayPicker: document.getElementById('clientWeekdayPicker'),
  clientVariableScheduleGrid: document.getElementById('clientVariableScheduleGrid'),
  variableScheduleBlock: document.getElementById('variableScheduleBlock'),
  fixedScheduleBlock: document.getElementById('fixedScheduleBlock'),
  fixedScheduleHint: document.getElementById('fixedScheduleHint'),
  fixedScheduleQuickText: document.getElementById('fixedScheduleQuickText'),
  fixedSchedulePreview: document.getElementById('fixedSchedulePreview'),
  clientCheckMode: document.getElementById('clientCheckMode'),
  clientNotes: document.getElementById('clientNotes'),
  packagePreview: document.getElementById('packagePreview'),
  deleteClientBtn: document.getElementById('deleteClientBtn'),

  packagesModalBackdrop: document.getElementById('packagesModalBackdrop'),
  packageForm: document.getElementById('packageForm'),
  packageId: document.getElementById('packageId'),
  packageName: document.getElementById('packageName'),
  packageLessons: document.getElementById('packageLessons'),
  packageWeeks: document.getElementById('packageWeeks'),
  packagePerWeek: document.getElementById('packagePerWeek'),
  packageDuration: document.getElementById('packageDuration'),
  packagePrice: document.getElementById('packagePrice'),
  packageList: document.getElementById('packageList'),
  deletePackageBtn: document.getElementById('deletePackageBtn'),

  dayModalBackdrop: document.getElementById('dayModalBackdrop'),
  dayModalTitle: document.getElementById('dayModalTitle'),
  dayModalSubtitle: document.getElementById('dayModalSubtitle'),
  daySlotGrid: document.getElementById('daySlotGrid'),
  dayLessonsWrap: document.getElementById('dayLessonsWrap'),
  dayLessonList: document.getElementById('dayLessonList'),
  dayAddLessonBtn: document.getElementById('dayAddLessonBtn'),

  lessonModalBackdrop: document.getElementById('lessonModalBackdrop'),
  lessonModalTitle: document.getElementById('lessonModalTitle'),
  lessonModalSubtitle: document.getElementById('lessonModalSubtitle'),
  lessonQuickTimes: document.getElementById('lessonQuickTimes'),
  lessonTimeInput: document.getElementById('lessonTimeInput'),
  lessonNoteInput: document.getElementById('lessonNoteInput'),
  rescheduleList: document.getElementById('rescheduleList'),
  duoSection: document.getElementById('duoSection'),
  duoPartnerRow: document.getElementById('duoPartnerRow'),
  duoPartnerBadge: document.getElementById('duoPartnerBadge'),
  duoUnlinkBtn: document.getElementById('duoUnlinkBtn'),
  duoAddRow: document.getElementById('duoAddRow'),
  duoClientSelect: document.getElementById('duoClientSelect'),
  duoLinkBtn: document.getElementById('duoLinkBtn'),

  timeModalBackdrop: document.getElementById('timeModalBackdrop'),
  timeModalTitle: document.getElementById('timeModalTitle'),
  timeModalSubtitle: document.getElementById('timeModalSubtitle'),
  timeSuggestionChips: document.getElementById('timeSuggestionChips'),
  timeManualInput: document.getElementById('timeManualInput'),

  renewModalBackdrop: document.getElementById('renewModalBackdrop'),
  renewForm: document.getElementById('renewForm'),
  renewPrice: document.getElementById('renewPrice'),
  renewPriceHint: document.getElementById('renewPriceHint'),
  renewPackage: document.getElementById('renewPackage'),
  renewStartDate: document.getElementById('renewStartDate'),
  renewCheckMode: document.getElementById('renewCheckMode'),
  renewPreview: document.getElementById('renewPreview'),

  reportModalBackdrop: document.getElementById('reportModalBackdrop'),
  reportMonthLabel: document.getElementById('reportMonthLabel'),
  reportStats: document.getElementById('reportStats'),
  reportFilterBar: document.getElementById('reportFilterBar'),
  reportMoodTitle: document.getElementById('reportMoodTitle'),
  reportMoodText: document.getElementById('reportMoodText'),
  reportMoodTextPanel: document.getElementById('reportMoodTextPanel'),
  reportNewClients: document.getElementById('reportNewClients'),
  reportTopPackages: document.getElementById('reportTopPackages'),
  reportFreeSession: document.getElementById('reportFreeSession'),
  reportPack99: document.getElementById('reportPack99'),
  reportPersonal: document.getElementById('reportPersonal'),
  reportSectionFreeSession: document.getElementById('reportSectionFreeSession'),
  reportSectionPack99: document.getElementById('reportSectionPack99'),
  reportSectionPersonal: document.getElementById('reportSectionPersonal'),
  reportOutstanding: document.getElementById('reportOutstanding'),
  reportInstallments: document.getElementById('reportInstallments'),
  reportSectionOutstanding: document.getElementById('reportSectionOutstanding'),
  reportSectionInstallments: document.getElementById('reportSectionInstallments'),
  reportCancelRanking: document.getElementById('reportCancelRanking'),
  reportFollowups: document.getElementById('reportFollowups'),
  exportManagedXlsxBtn: document.getElementById('exportManagedXlsxBtn'),

  authShell: document.getElementById('authShell'),
  sbProjectUrl: document.getElementById('sbProjectUrl'),
  sbAnonKey: document.getElementById('sbAnonKey'),
  saveSupabaseConfigBtn: document.getElementById('saveSupabaseConfigBtn'),
  useDemoLocalBtn: document.getElementById('useDemoLocalBtn'),
  supabaseConfigStatus: document.getElementById('supabaseConfigStatus'),
  authMessage: document.getElementById('authMessage'),
  userBadge: document.getElementById('userBadge'),
  syncBadge: document.getElementById('syncBadge'),
  openAccountBtn: document.getElementById('openAccountBtn'),
  loginPanel: document.getElementById('loginPanel'),
  signupPanel: document.getElementById('signupPanel'),
  resetPanel: document.getElementById('resetPanel'),
  authLoginEmail: document.getElementById('authLoginEmail'),
  authLoginPassword: document.getElementById('authLoginPassword'),
  authSignupEmail: document.getElementById('authSignupEmail'),
  authSignupPassword: document.getElementById('authSignupPassword'),
  authResetEmail: document.getElementById('authResetEmail'),
  showResetTabBtn: document.getElementById('showResetTabBtn'),

  passwordUpdateModalBackdrop: document.getElementById('passwordUpdateModalBackdrop'),
  passwordUpdateForm: document.getElementById('passwordUpdateForm'),
  passwordUpdateInput: document.getElementById('passwordUpdateInput'),

  accountModalBackdrop: document.getElementById('accountModalBackdrop'),
  cloudUserEmail: document.getElementById('cloudUserEmail'),
  cloudStatusLabel: document.getElementById('cloudStatusLabel'),
  cloudProjectUrl: document.getElementById('cloudProjectUrl'),
  cloudAnonKey: document.getElementById('cloudAnonKey'),
  saveCloudConfigBtn: document.getElementById('saveCloudConfigBtn'),
  manualSyncBtn: document.getElementById('manualSyncBtn'),
  sendResetPasswordBtn: document.getElementById('sendResetPasswordBtn'),
  logoutBtnModal: document.getElementById('logoutBtnModal'),
  googleStatusLabel: document.getElementById('googleStatusLabel'),
  googleStatusHint: document.getElementById('googleStatusHint'),
  connectGoogleBtn: document.getElementById('connectGoogleBtn'),
  googleResyncBtn: document.getElementById('googleResyncBtn'),
  disconnectGoogleBtn: document.getElementById('disconnectGoogleBtn')

};
